### ISSUE TITLE
为什么停止更新了？

### ISSUE THREAD

**Issue by koaracn** [cipchk/ngx-webuploader#1]
如题。

**Comment by cipchk** [comment]
请问有什么问题？

**Comment by koaracn** [comment]
好像不能多实例化组件 我是在angular6里用的 Wei Zhao 邮箱：will.lawson.1987@gmail.com 签名由 网易邮箱大师 定制 在2018年08月11日 09:29，卡色 写道： 请问有什么问题？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cipchk** [comment]
请告知具体有助于发现问题所在的信息。
